"""
Base Strategy — Abstract base class for all trading strategies.
All strategies must inherit from this and implement the generate_signal method.
"""

from abc import ABC, abstractmethod
from typing import Optional
from dataclasses import dataclass, field
from datetime import datetime
import pandas as pd
from bot.config.settings import TradeDirection


@dataclass
class TradeSignal:
    """Represents a trading signal generated by a strategy."""

    direction: TradeDirection
    symbol: str
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float = 0.0  # 0.0 to 1.0
    strategy_name: str = ""
    timeframe: str = ""
    reason: str = ""
    timestamp: datetime = field(default_factory=datetime.now)

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate the Risk:Reward ratio of this signal."""
        if self.direction == TradeDirection.HOLD:
            return 0.0

        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)

        if risk == 0:
            return 0.0
        return round(reward / risk, 2)

    @property
    def risk_pips(self) -> float:
        """Risk in price distance."""
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_pips(self) -> float:
        """Reward in price distance."""
        return abs(self.take_profit - self.entry_price)

    def __str__(self) -> str:
        if self.direction == TradeDirection.HOLD:
            return f"[{self.strategy_name}] {self.symbol} — HOLD (no trade)"

        return (
            f"[{self.strategy_name}] {self.symbol} {self.direction.value.upper()} | "
            f"Entry: {self.entry_price:.5f} | SL: {self.stop_loss:.5f} | "
            f"TP: {self.take_profit:.5f} | R:R {self.risk_reward_ratio} | "
            f"Confidence: {self.confidence:.0%}"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Every strategy must implement:
    - generate_signal(): Analyze data and return a TradeSignal
    - name: A human-readable name for the strategy
    """

    def __init__(self):
        self._name = "Base Strategy"
        self._description = ""
        self._suitable_regimes = []  # Which market regimes this strategy works in

    @property
    def name(self) -> str:
        return self._name

    @property
    def description(self) -> str:
        return self._description

    @property
    def suitable_regimes(self) -> list:
        return self._suitable_regimes

    @abstractmethod
    def generate_signal(
        self,
        symbol: str,
        higher_tf_data: pd.DataFrame,
        entry_tf_data: pd.DataFrame,
        current_price: dict,
    ) -> Optional[TradeSignal]:
        """
        Analyze market data and generate a trade signal.

        Args:
            symbol: Trading pair
            higher_tf_data: Analyzed DataFrame for higher timeframe (H4)
            entry_tf_data: Analyzed DataFrame for entry timeframe (M15)
            current_price: Current bid/ask dict

        Returns:
            TradeSignal if a valid setup is found, None otherwise
        """
        pass

    def validate_signal(self, signal: TradeSignal) -> bool:
        """
        Validate a trade signal meets minimum requirements.

        Args:
            signal: The generated trade signal

        Returns:
            True if signal is valid
        """
        if signal is None:
            return False

        if signal.direction == TradeDirection.HOLD:
            return False

        # Must have valid SL and TP
        if signal.stop_loss <= 0 or signal.take_profit <= 0:
            return False

        # SL and TP must be on correct sides
        if signal.direction == TradeDirection.BUY:
            if signal.stop_loss >= signal.entry_price:
                return False
            if signal.take_profit <= signal.entry_price:
                return False

        elif signal.direction == TradeDirection.SELL:
            if signal.stop_loss <= signal.entry_price:
                return False
            if signal.take_profit >= signal.entry_price:
                return False

        # Minimum R:R check
        from bot.config.settings import settings
        if signal.risk_reward_ratio < settings.min_reward_ratio:
            return False

        # Minimum confidence gate
        from bot.config.settings import settings
        if signal.confidence < settings.min_confidence:
            return False

        return True
